<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="macros.xacro"/>

    <!-- PROPERTIES -->
    <xacro:property name="chassis_length" value="0.7" />
    <xacro:property name="chassis_width" value="0.65" />
    <xacro:property name="chassis_height" value="0.1" />
    <xacro:property name="wheel_radius" value="0.09" />
    <xacro:property name="wheel_thickness" value="0.04" />
    <xacro:property name="wheel_seperation" value="0.21" />


    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">

    </link>

    
    <!-- CHASSIS LINK -->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="0 0 0"/>
    </joint>

    <link name="chassis_link">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="1" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis_link">
        <material>Gazebo/White</material>
    </gazebo>
    


    <!-- WHEEL LINKS LEFT 1 (CASTER) -->
    <joint name="left_wheel_1_joint" type="fixed">
        <parent link="base_link"/>
        <child link="left_wheel_1_link"/>
        <origin xyz="${wheel_seperation} ${chassis_width/2 + wheel_thickness/2} 0" rpy="-${pi/2} 0 0" />
    </joint>

    <link name="left_wheel_1_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.2" length="${wheel_thickness}" radius="${wheel_thickness}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel_1_link">
        <material>Gazebo/Blue</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>


    <!-- WHEEL LINKS LEFT 2 -->
    <joint name="left_wheel_2_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_2_link"/>
        <origin xyz="0 ${chassis_width/2 + wheel_thickness/2} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel_2_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.2" length="${wheel_thickness}" radius="${wheel_thickness}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel_2_link">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- WHEEL LINKS LEFT 3 (CASTER) -->
    <joint name="left_wheel_3_joint" type="fixed">
        <parent link="base_link"/>
        <child link="left_wheel_3_link"/>
        <origin xyz="-${wheel_seperation} ${chassis_width/2 + wheel_thickness/2} 0" rpy="-${pi/2} 0 0" />
    </joint>

    <link name="left_wheel_3_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.2" length="${wheel_thickness}" radius="${wheel_thickness}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel_3_link">
        <material>Gazebo/Blue</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>



    
    <!-- WHEEL LINKS RIGHT 1 (CASTER) -->
    <joint name="right_wheel_1_joint" type="fixed">
        <parent link="base_link"/>
        <child link="right_wheel_1_link"/>
        <origin xyz="${wheel_seperation} -${chassis_width/2 + wheel_thickness/2} 0" rpy="${pi/2} 0 0" />
    </joint>

    <link name="right_wheel_1_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.2" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel_1_link">
        <material>Gazebo/Blue</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>


    <!-- WHEEL LINKS RIGHT 2 -->
    <joint name="right_wheel_2_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_2_link"/>
        <origin xyz="0 -${chassis_width/2 + wheel_thickness/2} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel_2_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.2" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel_2_link">
        <material>Gazebo/Blue</material>
    </gazebo>


    <!-- WHEEL LINKS RIGHT 3 (CASTER) -->
    <joint name="right_wheel_3_joint" type="fixed">
        <parent link="base_link"/>
        <child link="right_wheel_3_link"/>
        <origin xyz="-${wheel_seperation} -${chassis_width/2 + wheel_thickness/2} 0" rpy="${pi/2} 0 0" />
    </joint>

    <link name="right_wheel_3_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.2" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel_3_link">
        <material>Gazebo/Blue</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>
</robot>